version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfileabc
    ports:
      - "8080:8080"

  service2:
    build:
      context: .
      dockerfile: Dockerfilexyz
    ports:
      - "5000:5000"