version: '3'
services:
  service1:
    build:
      context: ./clientes-consumer
      dockerfile: Dockerfileabc
    ports:
      - "8080:8080"

  service2:
    build:
      context: ./clientes-consumer
      dockerfile: Dockerfilexyz
    ports:
      - "5000:5000"

  service3:
    build:
      context: ./camel-integrationinline-fabad
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2